[package]
name = "spyward"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
libc = "0.2.172"

[build-dependencies]
bindgen = "0.71.1"
pkg-config = "0.3.32"
