[package]
name = "spyward"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
ctrlc = "3.4.7"
libc = "0.2.172"
thiserror = "2.0.12"

[build-dependencies]
bindgen = "0.71.1"
pkg-config = "0.3.32"
